builds:
- env:
  - GO111MODULE=on
  goos:
    - darwin
  goarch:
    - amd64
archive:
  replacements:
    darwin: Darwin
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
